theme: original-new-shasha-theme
title: Sateula's homepage
description: Simplified yet powerful HTML website! made by Sateula. Mixed all my new and old works.
author: Sateula
other_authors: [xdarkshan, Shasha, SateulaDev, Shantan Indonesia]
